# Generated by Django 3.2.4 on 2021-08-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_name', models.CharField(max_length=50)),
                ('cust_id', models.IntegerField()),
                ('cust_email', models.EmailField(max_length=254)),
                ('current_balance', models.IntegerField()),
            ],
        ),
    ]
