# Generated by Django 3.2.4 on 2021-08-09 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparks_bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
