# Generated by Django 3.2.4 on 2021-08-10 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparks_bank', '0002_customer_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='transaction_record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactor', models.CharField(max_length=50)),
                ('revolver', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
